"""Add MobyGames data

Revision ID: 0015_mobygames_data
Revises: 0014_asset_files
Create Date: 2024-02-13 17:57:25.936825

"""

import sqlalchemy as sa
from alembic import op

from utils.database import CustomJSON, is_postgresql
from utils.migration_helpers import add_column_if_not_exists, drop_column_if_exists

# revision identifiers, used by Alembic.
revision = "0015_mobygames_data"
down_revision = "0014_asset_files"
branch_labels = None
depends_on = None


def upgrade() -> None:
    connection = op.get_bind()

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        add_column_if_not_exists(
            batch_op, sa.Column("moby_id", sa.Integer(), nullable=True)
        )

    with op.batch_alter_table("roms", schema=None) as batch_op:
        add_column_if_not_exists(
            batch_op, sa.Column("moby_id", sa.Integer(), nullable=True)
        )
        add_column_if_not_exists(
            batch_op, sa.Column("moby_metadata", CustomJSON(), nullable=True)
        )

    with op.batch_alter_table("roms", schema=None) as batch_op:
        if is_postgresql(connection):
            batch_op.execute("update roms set moby_metadata = jsonb_build_object()")
        else:
            batch_op.execute("update roms set moby_metadata = JSON_OBJECT()")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms", schema=None) as batch_op:
        drop_column_if_exists(batch_op, "moby_metadata")
        drop_column_if_exists(batch_op, "moby_id")

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        drop_column_if_exists(batch_op, "moby_id")

    # ### end Alembic commands ###
