"""Add created_at and updated_at columns

Revision ID: 0020_created_and_updated
Revises: 0019_resources_refactor
Create Date: 2024-06-27 12:08:13.886766

"""

import sqlalchemy as sa
from alembic import op

from utils.migration_helpers import add_column_if_not_exists, drop_column_if_exists

# revision identifiers, used by Alembic.
revision = "0020_created_and_updated"
down_revision = "0019_resources_refactor"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("firmware", schema=None) as batch_op:
        add_column_if_not_exists(
            op,
            "firmware",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        add_column_if_not_exists(
            op,
            "firmware",
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        add_column_if_not_exists(
            op,
            "platforms",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        add_column_if_not_exists(
            op,
            "platforms",
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )

    with op.batch_alter_table("rom_notes", schema=None) as batch_op:
        add_column_if_not_exists(
            op,
            "rom_notes",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        batch_op.alter_column(
            "last_edited_at",
            existing_type=sa.DateTime(timezone=True),
            new_column_name="updated_at",
            server_default=sa.text("now()"),
            nullable=False,
        )

    with op.batch_alter_table("roms", schema=None) as batch_op:
        add_column_if_not_exists(
            op,
            "roms",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        add_column_if_not_exists(
            op,
            "roms",
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        add_column_if_not_exists(
            op,
            "users",
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )
        add_column_if_not_exists(
            op,
            "users",
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        drop_column_if_exists(op, "users", "updated_at")
        drop_column_if_exists(op, "users", "created_at")

    with op.batch_alter_table("roms", schema=None) as batch_op:
        drop_column_if_exists(op, "roms", "updated_at")
        drop_column_if_exists(op, "roms", "created_at")

    with op.batch_alter_table("rom_notes", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DateTime(timezone=True),
            new_column_name="last_edited_at",
            nullable=False,
        )

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        drop_column_if_exists(op, "platforms", "updated_at")
        drop_column_if_exists(op, "platforms", "created_at")

    with op.batch_alter_table("firmware", schema=None) as batch_op:
        drop_column_if_exists(op, "firmware", "updated_at")
        drop_column_if_exists(op, "firmware", "created_at")

    # ### end Alembic commands ###
