"""platforms_custom_name

Revision ID: 0029_platforms_custom_name
Revises: 0028_user_email
Create Date: 2024-12-24 01:32:57.121432

"""

import sqlalchemy as sa
from alembic import op

from utils.migration_helpers import add_column_if_not_exists, drop_column_if_exists

# revision identifiers, used by Alembic.
revision = "0029_platforms_custom_name"
down_revision = "0028_user_email"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        add_column_if_not_exists(
            op,
            "platforms",
            sa.Column("custom_name", sa.String(length=400), nullable=True),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        drop_column_if_exists(op, "platforms", "custom_name")
    # ### end Alembic commands ###
