"""Add ScreenScraper data

Revision ID: 0035_screenscraper
Revises: 0034_virtual_collections_db_view
Create Date: 2025-01-02 18:58:55.557123

"""

import sqlalchemy as sa
from alembic import op

from utils.database import CustomJSON
from utils.migration_helpers import add_column_if_not_exists, drop_column_if_exists

# revision identifiers, used by Alembic.
revision = "0035_screenscraper"
down_revision = "0034_virtual_collections_db_view"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("platforms", schema=None) as batch_op:
        add_column_if_not_exists(
            batch_op, sa.Column("ss_id", sa.Integer(), nullable=True)
        )

    with op.batch_alter_table("roms", schema=None) as batch_op:
        add_column_if_not_exists(
            batch_op, sa.Column("ss_id", sa.Integer(), nullable=True)
        )
        add_column_if_not_exists(
            batch_op, sa.Column("ss_metadata", CustomJSON(), nullable=True)
        )
        add_column_if_not_exists(
            batch_op, sa.Column("url_manual", sa.Text(), nullable=True)
        )
        add_column_if_not_exists(
            batch_op, sa.Column("path_manual", sa.Text(), nullable=True)
        )
        batch_op.create_index("idx_roms_ss_id", ["ss_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms", schema=None) as batch_op:
        batch_op.drop_index("idx_roms_ss_id")
        drop_column_if_exists(batch_op, "ss_id")
        drop_column_if_exists(batch_op, "ss_metadata")
        drop_column_if_exists(batch_op, "url_manual")
        drop_column_if_exists(batch_op, "path_manual")

    with op.batch_alter_table("platforms", schema=None) as batch_op:
        drop_column_if_exists(batch_op, "ss_id")
    # ### end Alembic commands ###
