"""update to 1.6.3

Revision ID: 1.6.3
Revises: 1.6.2
Create Date: 2023-04-10 23:13:43.591414

"""

import sqlalchemy as sa
from alembic import op

from utils.database import CustomJSON
from utils.migration_helpers import add_column_if_not_exists, drop_column_if_exists

# revision identifiers, used by Alembic.
revision = "1.6.3"
down_revision = "1.6.2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms") as batch_op:
        add_column_if_not_exists(
            batch_op, sa.Column("multi", sa.Boolean(), nullable=True)
        )
        add_column_if_not_exists(
            batch_op, sa.Column("files", CustomJSON(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms") as batch_op:
        drop_column_if_exists(batch_op, "files")
        drop_column_if_exists(batch_op, "multi")
    # ### end Alembic commands ###
