"""update to 1.8.1

Revision ID: 1.8.1
Revises: 1.8
Create Date: 2023-04-17 12:03:19.163501

"""

import sqlalchemy as sa
from alembic import op

from utils.database import CustomJSON, is_postgresql
from utils.migration_helpers import add_column_if_not_exists, drop_column_if_exists

# revision identifiers, used by Alembic.
revision = "1.8.1"
down_revision = "1.8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    connection = op.get_bind()

    json_array_build_func = (
        "jsonb_build_array()" if is_postgresql(connection) else "JSON_ARRAY()"
    )

    with op.batch_alter_table("roms") as batch_op:
        add_column_if_not_exists(
            op,
            "roms",
            sa.Column(
                "url_screenshots",
                CustomJSON(),
                nullable=False,
                server_default=sa.text(f"({json_array_build_func})"),
            ),
        )
        add_column_if_not_exists(
            op,
            "roms",
            sa.Column(
                "path_screenshots",
                CustomJSON(),
                nullable=False,
                server_default=sa.text(f"({json_array_build_func})"),
            ),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roms") as batch_op:
        drop_column_if_exists(op, "roms", "url_screenshots")
        drop_column_if_exists(op, "roms", "path_screenshots")
    # ### end Alembic commands ###
